### ISSUE TITLE
Changing how events are handled

### ISSUE THREAD

**Issue by eaten-squid** [DariusMontez/gamepad#28]
Looking at the code, I think changing the way in which events are handled could improve both efficiency and easy of use. 
 
For example using a dictionary in the form of `"string_event":[function1, function 2]` would change the current usage of the class handler and possibly make using a decorator/create a handler eaiser.

Also using a decorator would benefit users of the package by making it easier to listen to a gamepad event

**Comment by DariusMontez** [comment]
I love the idea of using decorators. Definitely should get implemented.

I think my handlers started as a dictionary as you described and eventually I switched to the `Handler` class. I can't remember why, but it might have something to do with storing arguments along with the callback, similar to GTK+ events. Of course this feature could be accomplished with `dict` too. 
Personally, I find the Handler objects easier to work with because they are self-contained, but perhaps it is overly complex.
The handler storage is not public, so it should not affect the user-facing API. The event system could use some tidying overall.
What do you say we implement decorators first, and then streamline the event system?

**Comment by eaten-squid** [comment]
Yeah, I will agree with that. I'm going to close this issue and create one just for decorators since they can be done separately.

As for doing which first is up to you. Decorators would help with usability while changing how events are handled could bring other benefits.
